import {
  riArrowGoForwardLine,
  riGlobalLine,
  riFileTextLine,
  riEqualizerLine,
  riTimerLine,
  riCalendarLine,
  riFlashlightLine,
  riLightbulbFlashLine,
  riDatabase2Line,
  riWindowLine,
  riCursorLine,
  riDownloadLine,
  riCommandLine,
  riExternalLinkLine,
} from 'v-remixicon/icons';

export default {
  riArrowGoForwardLine,
  riGlobalLine,
  riFileTextLine,
  riEqualizerLine,
  riTimerLine,
  riCalendarLine,
  riFlashlightLine,
  riLightbulbFlashLine,
  riDatabase2Line,
  riWindowLine,
  riCursorLine,
  riDownloadLine,
  riCommandLine,
  riExternalLinkLine,
};
